version: '3.7'
services:
  cache:
    image: 'redis:6.2-alpine'
    container_name: observatio-redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  mariaDB:
    container_name: observatio-mariadb
    hostname: mariadb
    image: 'mariadb:11.8.3'
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: observatio-pma
    links:
      - mariaDB
    environment:
      PMA_HOST: mariaDB
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    ports:
      - '8082:80'
