export enum Permissions {
  ADD_CAMERA = 'ADD_CAMERA',
  SHOW_CAMERA = 'SHOW_CAMERA',
  EDIT_CAMERA = 'EDIT_CAMERA',
  DELETE_CAMERA = 'DELETE_CAMERA',
  ADD_USER = 'ADD_USER',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
}
